import type { DashboardCommentRow } from "@/domain/dashboard/schemas";

/** Fixtures para tests del tablero. El dashboard en producción usa solo datos de Supabase. */

export const dashboardMockComments: DashboardCommentRow[] = [
  {
    id: "comentario-001",
    customer: "Cliente verificado",
    business: "Cafeteria",
    branch: "Centro",
    feedbackType: "Felicitación",
    sentiment: "Positivo",
    csatScore: 5,
    status: "Nuevo",
    message: "La atencion fue rapida y resolvieron mi solicitud sin vueltas.",
    receivedAt: "Hace 12 min",
  },
  {
    id: "comentario-002",
    customer: "Compra reciente",
    business: "Cafeteria",
    branch: "Mall Norte",
    feedbackType: "Queja",
    sentiment: "Riesgo",
    csatScore: 2,
    status: "En revisión",
    message: "El tiempo de espera fue alto y nadie explico el retraso.",
    receivedAt: "Hace 28 min",
  },
  {
    id: "comentario-003",
    customer: "Visitante frecuente",
    business: "Retail",
    branch: "Boulevard",
    feedbackType: "Observación",
    sentiment: "Neutral",
    csatScore: 3,
    status: "Nuevo",
    message: "El producto estaba bien, pero el area de caja se sentia lenta.",
    receivedAt: "Hace 1 h",
  },
  {
    id: "comentario-004",
    customer: "Cliente digital",
    business: "Retail",
    branch: "Centro",
    feedbackType: "Recomendación",
    sentiment: "Riesgo",
    csatScore: 2,
    status: "Nuevo",
    message: "La promocion no estaba clara y el personal no pudo explicarla.",
    receivedAt: "Hace 2 h",
  },
  {
    id: "comentario-005",
    customer: "Visita familiar",
    business: "Restaurante",
    branch: "Boulevard",
    feedbackType: "Felicitación",
    sentiment: "Positivo",
    csatScore: 5,
    status: "Resuelto",
    message: "El equipo fue amable y la mesa estuvo lista rapidamente.",
    receivedAt: "Hace 3 h",
  },
  {
    id: "comentario-006",
    customer: "Cliente recurrente",
    business: "Restaurante",
    branch: "Mall Norte",
    feedbackType: "Queja",
    sentiment: "Riesgo",
    csatScore: 1,
    status: "En revisión",
    message: "El pedido salio incompleto y tuve que pedir ayuda dos veces.",
    receivedAt: "Hace 4 h",
  },
  {
    id: "comentario-007",
    customer: "Nueva compra",
    business: "Cafeteria",
    branch: "Centro",
    feedbackType: "Observación",
    sentiment: "Neutral",
    csatScore: 3,
    status: "Nuevo",
    message: "Buena atencion, aunque el area de espera estaba saturada.",
    receivedAt: "Hace 5 h",
  },
];
