-- ============================================================
-- 12. AGENT REPORTS
-- Persisted operational readings generated by the agent.
-- ============================================================
create table public.agent_reports (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations on delete cascade,
  branch_id uuid references public.branches on delete set null,
  actor_user_id uuid references public.profiles on delete set null,
  report_type text not null check (report_type in ('operational_report')),
  period text not null check (period in ('7d', '30d')),
  headline text not null check (char_length(headline) between 3 and 200),
  summary text not null check (char_length(summary) between 3 and 4000),
  next_actions jsonb not null default '[]'::jsonb,
  delivery_readiness text not null check (char_length(delivery_readiness) between 3 and 1000),
  context jsonb not null default '{}'::jsonb,
  generated_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index agent_reports_org_created_idx
  on public.agent_reports (organization_id, created_at desc);

create index agent_reports_branch_created_idx
  on public.agent_reports (branch_id, created_at desc)
  where branch_id is not null;

alter table public.agent_reports enable row level security;

create policy "agent_reports: organization members select"
  on public.agent_reports for select
  using (
    organization_id in (select public.user_organization_ids())
  );

create policy "agent_reports: owner/manager insert"
  on public.agent_reports for insert
  with check (
    organization_id in (
      select organization_id
      from public.organization_members
      where user_id = auth.uid()
        and role in ('owner', 'manager')
    )
  );
